---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{R, echo=FALSE}
## Setting up the working directory
setwd("C:/Users/skarpath/Documents/Coursera_Projects_Data_Science_Specialization/5_Reproducible_Research/assignment_week2")
```

## 1. Code for reading in the dataset and processing the data
```{R}
activityDataset <- read.csv(file = 'activity.csv')
head(activityDataset)
```
#### Omitting the NAs from the dataset
```{R}
activityDatasetProcessed <- na.omit(activityDataset)
head(activityDatasetProcessed)
```
#### Process the date column
```{R}
activityDatasetProcessed$date <- as.Date.character(activityDatasetProcessed$date, "%Y-%m-%d")
```

## 2. Histogram of the total number of steps taken each day
#### First we need to preprocess the dataset and bring it in a form that it's good to work with.
```{R}
totalStepsPerDay <- as.data.frame.table(tapply(activityDatasetProcessed$steps, as.Date.character(activityDatasetProcessed$date,  "%Y-%m-%d"), sum))
names(totalStepsPerDay) <- c("date", "steps")
head(totalStepsPerDay)
```
#### Plotting the dataset and results
```{R}
library(ggplot2)
gsum <- ggplot(data=totalStepsPerDay, aes(x=as.Date(date), y=steps)) + 
            geom_histogram(stat='identity') +
            labs(title = "Total number of steps taken per day", 
                 x = "Date", 
                 y = "Total Steps")

print(gsum)
```

## 3. Mean and median number of steps taken each day
```{R}
meanStepsPerDay <- mean(totalStepsPerDay$steps)
meanStepsPerDay

medianStepsPerDay <- median(totalStepsPerDay$steps)
medianStepsPerDay
```

## 4. Time series plot of the average number of steps taken
#### First we aggregate the steps using the mean function by interval.
```{R}
aggdata <-aggregate(activityDatasetProcessed$steps, 
                    by = list(activityDatasetProcessed$interval),
                    FUN = mean)
names(aggdata) <- c("interval", "AggSteps")
head(aggdata)
```
#### Plotting the dataset and results 
```{R}
gmean <- ggplot(data=aggdata, aes(x=interval, y=AggSteps)) + 
            geom_line() + 
            labs(title = "Time series plot of the avg num. of steps", 
                 x = "Interval", 
                 y = "Avg Steps")

print(gmean)
```

## 5. The 5-minute interval that, on average, contains the maximum number of steps
```{R}
subset(aggdata, aggdata$AggSteps == max(aggdata$AggSteps))
```

## 6. Code to describe and show a strategy for imputing missing data

#### I have processed my dataset at the beginning of this file to remove the NAs and produce a clean dataset which is called activityDatasetProcessed. The raw dataset is called activityDataset and it's the initial dataset that before any preprocessing step, so it includes  the NA (missing values)

#### Let's see how many missing values has the initial dataset.
```{R}
sum(is.na(activityDataset))
```
#### Now, let's see how many missing values has the processed dataset which I am using for my analysis. 
```{R}
sum(is.na(activityDatasetProcessed))
```
#### One strategy for imputing data is to replace the NAs with the mean/median. 
```{R}
dataImputingNAs <- data.frame(sapply(
        activityDataset,
        function(x) ifelse(is.na(x),
            mean(x, na.rm = TRUE),
            x)))
head(dataImputingNAs)
```
#### If we want to check now how many missing values we have, we can see that it's 0.
```{R}
sum(is.na(dataImputingNAs))
```

## 7. Histogram of the total number of steps taken each day after missing values are imputed
#### We have imputed the NA values from the original dataset in the previous step and storing the new data frame with the name dataImputingNAs.
```{R}
# Transform the date column into a "Date" column format and the steps into integer.
dataImputingNAs$date <- as.Date(dataImputingNAs$date)
dataImputingNAs$steps <- as.integer(dataImputingNAs$steps)
```
#### Aggregate the steps for each date and use sum as aggregation function.
```{R}
aggdataImputedNAs <-aggregate(dataImputingNAs$steps, 
                    by = list(dataImputingNAs$date),
                    FUN = sum)
names(aggdataImputedNAs) <- c("date", "AggSteps")
head(aggdataImputedNAs)
```
### Plotting dataset and results
```{R}
gsumImputed <- ggplot(data=aggdataImputedNAs, aes(x=date, y=AggSteps)) + 
            geom_histogram(stat='identity') + 
            labs(title = "Total number of steps taken each day(with imputed values)", 
                 x = "date", 
                 y = "Avg Steps")

print(gsumImputed)
```

## 8. Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
#### Creating this classification of whether a date is weekend or weekday.
```{R}
dataImputingNAs$weekdays <- weekdays(dataImputingNAs$date)
dataImputingNAs$weekend <- ifelse(dataImputingNAs$weekday=="Saturday" | dataImputingNAs$weekday=="Sunday", "Weekend", "Weekday")
```
#### Aggregate the steps for weekend or weekday and use mean as aggregation function.
```{R}
aggdataAVGImputedNAs <-aggregate(dataImputingNAs$steps, 
                    by = list(dataImputingNAs$weekend, dataImputingNAs$interval),
                    FUN = sum)
names(aggdataAVGImputedNAs) <- c("classification", "interval", "steps")
aggdataAVGImputedNAs$interval <- as.integer(aggdataAVGImputedNAs$interval)
```
#### Plot the AVG number of steps per 5 mins intervals across weekdays/weekends. 
```{R}
gAVGweekdayORweekends <- ggplot(data=aggdataAVGImputedNAs, 
                                aes(x=interval, 
                                    y=steps, 
                                    color = classification)) + 
                                    facet_grid(classification ~.) + 
                                    geom_line() + 
                                    labs( x = "intervals", 
                                     y = "Avg Steps",
                                     title = "AVG steps taken per 5-minute interval across weekdays and weekends")
print(gAVGweekdayORweekends)
```

## 9. All of the R code needed to reproduce the results (numbers, plots, etc.) in the report
#### This is being accomblised as presented above. 
